// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veterinary.Backend.Infrastructure.Persistence.Context;

#nullable disable

namespace Veterinary.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VeterinaryContext))]
    partial class VeterinaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Veterinary.Backend.Domain.AggregateRoots.Owner.Owner", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateAddedToSystem")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date_added_to_system");

                    b.HasKey("Id");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("Veterinary.Backend.Domain.AggregateRoots.Owner.Owner", b =>
                {
                    b.OwnsOne("Veterinary.Backend.Domain.ObjectValues.Email", "Email", b1 =>
                        {
                            b1.Property<string>("OwnerId")
                                .HasColumnType("VARCHAR(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("email");

                            b1.HasKey("OwnerId");

                            b1.ToTable("owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Veterinary.Backend.Domain.ObjectValues.Identification", "Identification", b1 =>
                        {
                            b1.Property<string>("OwnerId")
                                .HasColumnType("VARCHAR(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("identification");

                            b1.HasKey("OwnerId");

                            b1.ToTable("owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Veterinary.Backend.Domain.ObjectValues.Name", "Name", b1 =>
                        {
                            b1.Property<string>("OwnerId")
                                .HasColumnType("VARCHAR(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("name");

                            b1.HasKey("OwnerId");

                            b1.ToTable("owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Veterinary.Backend.Domain.ObjectValues.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<string>("OwnerId")
                                .HasColumnType("VARCHAR(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("phone_number");

                            b1.HasKey("OwnerId");

                            b1.ToTable("owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Identification")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
